name: Lighthouse Report

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        npm install -g lighthouse
        
    - name: Build
      run: |
        npm ci
        npm run build
        
    - name: Start Server
      run: |
        npm start &
        sleep 10 # Wait for server to start up
      
    - name: Generate Report
      run: |
        mkdir -p test-results
        lighthouse http://localhost:3000 --output html --output-path=./test-results/report.html
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Lighthouse Report
        path: ./test-results/report.html
