name: Website Performance Test

on:
  push:
    branches:
      - development

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Measure website performance
        uses: GoogleChrome/lighthouse-ci-action@v2
        with:
          urls: 'http://localhost:3000/privacy.html'
          budgetPath: './budget.json'
          reportPath: './report.json'
          chromeFlags: '--no-sandbox'

      - name: Print performance report
        run: cat ./report.json
