name: Website Performance Report

on:
  push:
    branches:
      - "development"

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start & sleep 10

      - name: Generate Lighthouse report
        run: npx lighthouse http://localhost:3000 --output html --output-path test-results/report.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./test-results
